apiVersion: apps/v1
kind: Deployment
metadata:
  name: Playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Playground
  template:
    metadata:
      labels:
        app: Playground
    spec:
      containers:
      - name: Playground
        image: alohababy42/playground:v1
        ports:
        - containerPort: 8888
