apiVersion: v1
kind: Service
metadata:
  name: aloha-playground-service
  namespace: dev
spec:
  selector:
    app: aloha-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
